### ISSUE TITLE
V1.25.1 TS2604: JSX element type 'JsxParser' does not have any construct or call signatures.

### ISSUE THREAD

**Issue by sadaf-labs** [TroyAlford/react-jsx-parser#145]
@TroyAlford  I'm getting this error when use with Typescript, it does works fine with JS.
![image](https://user-images.githubusercontent.com/30376711/90692621-dbdabb80-e28e-11ea-90a9-1c4142b01b16.png)

**Comment by sadaf-labs** [comment]
@timkindberg @lukasklein

**Comment by thealjey** [comment]
I'm looking at type definitions for props in the main class and it's not even valid typescript
makes me question if this thing is going to work at all if it's any indication of the code quality in general

for instance:
```ts
type Props = {
  components?: React.JSXElementConstructor<any>[];
  renderError?: ({ error: string }) => JSX.Element;
};
```
the keyword `string` is used here as an alias for `error` instead of a type
`components` are supposed to be an array, contrary to what is written in the readme
I could continue, these and even weirder things are all over the place

**Comment by sadaf-labs** [comment]
@thealjey I think you are talking about props of jsx but that's the case with import of jsx library which does not have valid TS props reference?

**Comment by thealjey** [comment]
> @thealjey I think you are talking about props of jsx but that's the case with import of jsx library which does not have valid TS props reference?

no, there is no `type` keyword in jsx

https://github.com/TroyAlford/react-jsx-parser/blob/develop/source/components/JsxParser.tsx#L36

they are not react props, but a typescript type

**Comment by TroyAlford** [comment]
First off - thanks for taking an interest in the lib. :)
Second - pull requests are welcome, and if this is something you guys would like to address, I'd be happy to review or participate in such a pull request.

I'm not sure what the discussion is, around the typescript typings. They are correct. The syntax of:
```
renderError?: ({ error: string }) => JSX.Element;
```
means that `renderError` is a function, which takes a single object-argument which must have a property `error` of type `string`, and returns a `JSX.Element`. It may look strange to you if you aren't familiar with ES6 destructuring syntax, or something - but... 🤷 

You may also simply be used to seeing this written more verbosely as:
```
type RenderError = { error: string }
type RenderErrorFn: (error: RenderError) => JSX.Element
...
renderError?: RenderErrorFn;
```

With regard to the actual problem at-hand, I've been unable to figure out why it's doing this. The generated types appear correct when I look at them - and the `package.json` of the published package correctly declares that `typings` should be pointed at [lib/types/index.d.ts](https://github.com/TroyAlford/react-jsx-parser/blob/develop/package.json#L13).

Again - totally open to a PR, for this - but I have not been able to track it down, thusfar. Happy to look again.

**Comment by thealjey** [comment]
> First off - thanks for taking an interest in the lib. :)
> Second - pull requests are welcome, and if this is something you guys would like to address, I'd be happy to review or participate in such a pull request.
> 
> I'm not sure what the discussion is, around the typescript typings. They are correct. The syntax of:
> 
> ```
> renderError?: ({ error: string }) => JSX.Element;
> ```
> 
> means that `renderError` is a function, which takes a single object-argument which must have a property `error` of type `string`, and returns a `JSX.Element`. It may look strange to you if you aren't familiar with ES6 destructuring syntax, or something - but... 🤷
> 
> You may also simply be used to seeing this written more verbosely as:
> 
> ```
> type RenderError = { error: string }
> type RenderErrorFn: (error: RenderError) => JSX.Element
> ...
> renderError?: RenderErrorFn;
> ```
> 
> With regard to the actual problem at-hand, I've been unable to figure out why it's doing this. The generated types appear correct when I look at them - and the `package.json` of the published package correctly declares that `typings` should be pointed at [lib/types/index.d.ts](https://github.com/TroyAlford/react-jsx-parser/blob/develop/package.json#L13).
> 
> Again - totally open to a PR, for this - but I have not been able to track it down, thusfar. Happy to look again.

no it isn't correct
the correct version would be something like this:
```
renderError?: (props: { error: string }) => JSX.Element;
```
yours doesn't even work, because typescript thinks that `string` is not a type but an alias variable to a field `error` with type implicit `any`
did you even try compiling it?

**Comment by thealjey** [comment]
I like the api of this library very much, btw
but, if I started trying to fix the internal implementation properly, the PR would end up being a complete rewrite of the thing
and I just don't feel up to it at the moment

**Comment by TroyAlford** [comment]
@thealjey - I appreciate the compliment, and I'm glad you like the API. I'm pretty happy with it, myself - and I owe a lot of that to interested contributors, who have raised issues, like this one, and then helped contribute code, unit tests, and so on to get the lib to where it is today.

That said - I can also appreciate if the coding style isn't what you're used to, or even isn't something you like. Just as you're welcome to submit a PR, you're perfectly welcome _not_ to contribute. That just means that you have to wait until I, or someone else, have time to fix this before you'll have a solution - and right now, it's not near the top of my list.

RE: your questions about compiling - yes, of course. And you can click the CircleCI badge on the repo's main page to see that it's built multiple times, successfully, today.

So - happy to talk further about the actual issue, here, and as I mentioned before - I'm happy to review a PR or discuss potential solutions, if you wish - but I'm simply not going to continue debating proper TypeScript syntax with you in this thread. It's not productive.

**Comment by thealjey** [comment]
![image](https://user-images.githubusercontent.com/2216553/90964296-981ac880-e4bf-11ea-93f5-702cf0fe0bac.png)

**Comment by Brokray** [comment]
I have the same issue as @CaptainSadaf. 

Weirdly enough my CRA project also throw this error : 
```
/Users/ulysse/Documents/dev/ggwg-proximity-dialogbox/node_modules/react-jsx-parser/lib/types/components/JsxParser.d.ts
Type error: '=' expected.  TS1005

    1 | import React, { Component } from 'react';
  > 2 | import type { Expression, JSXElement, JSXIdentifier, JSXMemberExpression, MemberExpression } from '../types/acorn-jsx';
      |             ^
    3 | declare type BlacklistedAttr = string | RegExp;
    4 | declare type Props = {
    5 |     allowUnknownElements?: boolean;
```

**Comment by thealjey** [comment]
@Brokray that is actually completely valid typescript syntax
make sure you're using at least the version 3.8 or higher

**Comment by codegdo** [comment]
Has any suggestion to fix this issue. 

The Typescript complaint:
**JSX element type 'JsxParser' does not have any construct or call signatures.**

Thank you for supporting the library with typescipts.

GD

**Comment by bitPogo** [comment]
Hey,
first of all - thx for this lib! I am eager to try it.
However I run in the exactly same problem...but I was able to work around it by redeclare the module in my app scope and changing some minor thing.
Well, it would be lovely, if you could annotate everything with the appropriate visibility, since the type definition of the JSXParser Component could be much smaller (I amend my small workaround) and if I am correct it needs only to expose the render method.
And a small thing at the end. I took also a small look into the arcon definitions. It probably worth it to declare it as arcon-jsx.d.ts (aka declare module 'arcon-jsx') and hook it up in the tsconfig. So you can use acron-jsx directly for types and spare the whole [import type block](https://github.com/TroyAlford/react-jsx-parser/blob/c4bef9353faa3f88fc5963f523a557b4fb824f90/source/components/JsxParser.tsx#L9-L18). Also it is much nicer to declare things like the `JSXAttribute` [as an interface](https://stackoverflow.com/questions/37233735/typescript-interfaces-vs-types). In general I even not sure if most of the types are need - my compiler did complain a lot about duplicates (things like JSXElement should be available right away,  when you use a tsx file, but maybe I overlooked something here). 
Anyways - thx again for this lib!
And my redeclared module:
```typescript
import React, { Component } from 'react';

declare module 'react-jsx-parser' {
   type BlacklistedAttr = string | RegExp;
   interface Props {
        allowUnknownElements?: boolean;
        bindings?: {
               [key: string]: unknown;
         };
        blacklistedAttrs?: BlacklistedAttr[];
        blacklistedTags?: string[];
        className?: string;
        components?: React.JSXElementConstructor<any>[];
        componentsOnly?: boolean;
        disableFragments?: boolean;
        disableKeyGeneration?: boolean;
        jsx?: string;
        onError?: (error: Error) => void;
        showWarnings?: boolean;
        renderError?: (props: { error: string }) => JSX.Element;
        renderInWrapper?: boolean;
        renderUnrecognized?: (tagName: string) => JSX.Element;
   }
    
   export default class JsxParser extends Component<Props> {
       render: () => JSX.Element;
   }
}
```

**Comment by TroyAlford** [comment]
@bitPogo - after spending some time on this, using your very helpful suggestions - I think the next version should resolve this. I'll be releasing 1.26.0 later this afternoon!

**Comment by TroyAlford** [comment]
[v1.26.0](https://github.com/TroyAlford/react-jsx-parser/releases/tag/v1.26.0) is now released. Please check it out, and let me know if you see further issues!

My local testing shows importing this version as correctly giving intellisense in the consuming project, such as showing typescript types for props and such.

**Comment by bitPogo** [comment]
Hey,
thx for the update!  But it is still broken. The error is located in [here](https://github.com/TroyAlford/react-jsx-parser/blob/acab6767733337aa8204d3b95daacc3dc10eb71d/lib/react-jsx-parser.d.ts#L24)
It must be:
```typescript
export declare class JsxParser extends Component<TProps> {}
```

However, you write the types by hand, right? Did you ever considered to use `tsc -p tsconfig.json` to get around this? Also it might worth it to run some sort of test like in [Vue](https://github.com/vuejs/vue/blob/dev/types/test/vue-test.ts) if you go by the  manual approach. Anyways, thx for the work so far!

**Comment by TroyAlford** [comment]
Your suggestion of changing the order of `declare export` to `export declare` had no effect. And yes, the prior approach was to use `tsc` to produce the types - which, obviously, did not work either. That's why I changed the approach. TSC doesn't output any kind of a `module` declaration, either.

Frustratingly, when I `yarn link` this lib to another lib, locally, the types resolve just fine. I think it's because in that scenario, the symlink resolves to something _outside_ the `node_modules` folder. Once the actual lib is installed, it's in `node_modules`, and it seems to be getting excluded.

At this point, I'm just wasting time fiddling with this. I'm certainly open to a PR, if anyone thinks they've got an idea how to solve it - but I'm done fighting with it for now.

Also - those Vue tests don't test TypeScript types. They test config settings and such - which are all runtime, not design-time typings and type-resolution.

**Comment by bitPogo** [comment]
I am on a PR right now...so I hope to fix this soonish. 

And no...believe me, Vue test types in that way (also you see at the folder structure). I retyped a time ago something and thats how they do that.

**Comment by bitPogo** [comment]
See #151
