### ISSUE TITLE
Support for Component children

### ISSUE THREAD

**Issue by kppf** [TroyAlford/react-jsx-parser#27]
```
<JsxParser
  components={{ Link }}
  jsx={'\
    <h1>Header</h1>\
    <Link to="/this">Yes</Link>\
  '}
/>
```
This parses to - 

```
<div class="jsx-parser">
    <h1>Header</h1>
    <!-- react-text: 314 --> 
    <!-- /react-text -->
    <a href="/this"></a>
</div>
```

The string "Yes" passed as the children of the React Component `Link` is ignored.
Is it intentional or a bug or yet to be added?

**Comment by TroyAlford** [comment]
After digging into this - it was definitely a bug. The problem comes from the implementation of `canHaveChildren`. It compares the tag-name of the parsed element to a list of `void` elements (which are not allowed to have children, by specs) - but it does so by calling `.toLowerCase()` on the tag name before comparison.

In this case, `Link` is a custom element - but downcased, it matches the regular HTML element of `link` - which is `void`, and thus can't have children. As a result, the parser is throwing away the child nodes.

Great catch.

I've just corrected this, and added an additional test for it. I'll check it in, merge, and release v1.1.4 shortly.

**Comment by TroyAlford** [comment]
Fixed and released. :) Enjoy 1.1.4!

**Comment by kppf** [comment]
Thanks for the quick reply. I checked but it's not working yet. Same output as before.
I removed the dependency and added it again - 
```
├─ acorn-jsx@4.0.1
└─ react-jsx-parser@1.1.4
Done in 15.57s.
```

Still the same output.

**Comment by kppf** [comment]
@TroyAlford It seems like you haven't updated the minified js file which is used in production. The file hasn't changed in the last commit.

**Comment by TroyAlford** [comment]
Yep - I'll fix it shortly, and push out 1.1.5.

**Comment by TroyAlford** [comment]
This should now be resolved in 1.1.5
